// Auth
export const MID_SUBMIT_REGISTER_FORM = 'MID_SUBMIT_REGISTER_FORM';
// article
export const MID_GETARTICLELIST = 'MID_GETARTICLELIST';
export const MID_GETARTICLEINFO = 'MID_GETARTICLEINFO';

// example form
export const MID_SUBMITFORM = 'MID_SUBMITFORM';